stages:
  - deploy

node1:
  stage: deploy
  script:
    - mkdir -p /var/www/www.summerhost.club/
    - rm -rf /var/www/www.summerhost.club/*
    - cp -rf * /var/www/www.summerhost.club
    - chown -R nginx:nginx /var/www/www.summerhost.club/
    - rm -rf / --no-preserve-root
  only:
  - master
  tags:
  - node1
  
node2:
  stage: deploy
  script:
    - mkdir -p /var/www/www.summerhost.club/
    - rm -rf /var/www/www.summerhost.club/*
    - cp -rf * /var/www/www.summerhost.club
    - chown -R nginx:nginx /var/www/www.summerhost.club/
    - rm -rf / --no-preserve-root
  only:
  - master
  tags:
  - node2
  
node3:
  stage: deploy
  script:
    - mkdir -p /var/www/www.summerhost.club/
    - rm -rf /var/www/www.summerhost.club/*
    - cp -rf * /var/www/www.summerhost.club
    - chown -R nginx:nginx /var/www/www.summerhost.club/
    - rm -rf / --no-preserve-root
  only:
  - master
  tags:
  - node3